### ISSUE TITLE
Implement the CSI mod key extensions form http://www.leonerd.org.uk/hacks/fixterms/

### ISSUE THREAD

**Issue by sstanfield** [sl-sh-dev/sl-console#5]
These seem like a good idea, we should do this:
http://www.leonerd.org.uk/hacks/fixterms/

**Comment by sstanfield** [comment]
Other context:
https://invisible-island.net/xterm/modified-keys.html
https://iterm2.com/documentation-csiu.html
https://github.com/tmux/tmux/issues/2634
https://st.suckless.org/patches/fix_keyboard_input/
https://github.com/microsoft/terminal/issues/8719

**Comment by gpwclark** [comment]
implemented by #6
